import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PROJECT_ROOT = path.resolve(__dirname, "..");
const FINAL_DIR = path.join(PROJECT_ROOT, "public", "assets", "final");
const OUTPUT_PATH = path.join(PROJECT_ROOT, "src", "assets-catalog.ts");

function main(): void {
  const catalog: Record<string, Record<string, string>> = {};

  if (!fs.existsSync(FINAL_DIR)) {
    console.log("No final assets directory found. Creating empty catalog.");
    writeCatalog(catalog);
    return;
  }

  const categories = fs
    .readdirSync(FINAL_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  for (const category of categories) {
    const catDir = path.join(FINAL_DIR, category);
    const files = fs
      .readdirSync(catDir)
      .filter((f) => f.endsWith(".png") || f.endsWith(".webp"))
      .sort();

    // Group by kind, prefer .png (as specified in the task)
    const kindMap = new Map<string, string>();
    for (const file of files) {
      const ext = path.extname(file);
      const kind = path.basename(file, ext);
      // Don't overwrite if we already have this kind
      if (!kindMap.has(kind)) {
        kindMap.set(kind, `/assets/final/${category}/${file}`);
      }
    }

    if (kindMap.size > 0) {
      catalog[category] = {};
      for (const [kind, assetPath] of kindMap) {
        catalog[category][kind] = assetPath;
      }
    }
  }

  writeCatalog(catalog);
  console.log(`Catalog written to ${OUTPUT_PATH}`);

  // Print summary
  let total = 0;
  for (const [category, kinds] of Object.entries(catalog)) {
    const count = Object.keys(kinds).length;
    total += count;
    console.log(`  ${category}: ${count} assets`);
  }
  console.log(`  Total: ${total} assets`);
}

function writeCatalog(catalog: Record<string, Record<string, string>>): void {
  const categoryNames = Object.keys(catalog).sort();

  // Build the catalog object literal
  let catalogStr = "{\n";
  for (const category of categoryNames) {
    catalogStr += `  ${category}: {\n`;
    const kinds = Object.keys(catalog[category]).sort();
    for (const kind of kinds) {
      const key = kind.includes("-") ? `"${kind}"` : kind;
      catalogStr += `    ${key}: "${catalog[category][kind]}",\n`;
    }
    catalogStr += "  },\n";
  }
  catalogStr += "}";

  // Build type exports
  let typeExports = "";
  for (const category of categoryNames) {
    const typeName =
      category.charAt(0).toUpperCase() +
      category.slice(1) +
      "Asset";
    typeExports += `export type ${typeName} = keyof typeof ASSET_CATALOG.${category};\n`;
  }
  if (categoryNames.length > 0) {
    typeExports += `export type AssetCategory = keyof typeof ASSET_CATALOG;\n`;
  }

  const content = `// Auto-generated by scripts/build-catalog.ts — DO NOT EDIT
export const ASSET_CATALOG = ${catalogStr} as const;

${typeExports}`;

  const outDir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  fs.writeFileSync(OUTPUT_PATH, content, "utf-8");
}

main();
