// Auto-generated by scripts/build-catalog.ts — DO NOT EDIT
export const ASSET_CATALOG = {
  achievement: {
    "pb-update": "/assets/final/achievement/pb-update.png",
  },
  decoration: {
    "star-small": "/assets/final/decoration/star-small.png",
  },
  emotion: {
    celebrate: "/assets/final/emotion/celebrate.png",
  },
  state: {
    "empty-ranking": "/assets/final/state/empty-ranking.png",
  },
} as const;

export type AchievementAsset = keyof typeof ASSET_CATALOG.achievement;
export type DecorationAsset = keyof typeof ASSET_CATALOG.decoration;
export type EmotionAsset = keyof typeof ASSET_CATALOG.emotion;
export type StateAsset = keyof typeof ASSET_CATALOG.state;
export type AssetCategory = keyof typeof ASSET_CATALOG;
